"""Build the optional native kernels shipped with sksfolio.

The checked-in solver sources are generated by Cython, so normal source and
wheel builds do not require Cython itself.  Every extension is optional: a
machine without a compiler retains the feature-equivalent Python solvers.
"""

from __future__ import annotations

import os

from setuptools import Extension, setup


compile_args = ["/O2"] if os.name == "nt" else ["-O3", "-std=c11"]

native_sources = {
    "sksfolio._native_pava": "sksfolio/_native_pava.c",
    "sksfolio.relaxation.fista._native_budget_prox": (
        "sksfolio/relaxation/fista/_native_budget_prox.c"
    ),
    "sksfolio.relaxation.fista._native_linear_prox": (
        "sksfolio/relaxation/fista/_native_linear_prox.c"
    ),
    "sksfolio.relaxation.pdhg._native_safe_dual": (
        "sksfolio/relaxation/pdhg/_native_safe_dual.c"
    ),
    "sksfolio.relaxation.pdhg._native_solver": (
        "sksfolio/relaxation/pdhg/_native_solver.c"
    ),
    "sksfolio.relaxation.fista._native_solver": (
        "sksfolio/relaxation/fista/_native_solver.c"
    ),
    "sksfolio.relaxation.scsdg._native_solver": (
        "sksfolio/relaxation/scsdg/_native_solver.c"
    ),
}


setup(
    ext_modules=[
        Extension(
            module,
            sources=[source],
            extra_compile_args=compile_args,
            optional=True,
        )
        for module, source in native_sources.items()
    ]
)
